apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo
  labels:
    app: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # Ziel: 50 % des CPU-Requests (= 50m bei 100m Request)
