apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo
  labels:
    app: demo
spec:
  minAvailable: 2           # bei freiwilligen Unterbrechungen (z. B. Node-Wartung) immer mind. 2 Pods
  selector:
    matchLabels:
      app: demo
