apiVersion: v1
kind: Pod
metadata:
  name: test-client
  labels:
    app: test-client
spec:
  containers:
    - name: test-client
      image: quay.io/ghilling/ubi-tools:10-latest
      command: ["sleep", "infinity"]
