...@../../tools/diagrams/style

direction: right

route: Route\n(OpenShift) {class: resource}
service: Service {class: resource}
deployment: Deployment {class: resource}
replicaset: ReplicaSet {class: resource}
pod: Pod {class: resource; width: 140; height: 140}
configmap: ConfigMap {class: resource}
secret: Secret {class: resource}

deployment -> replicaset: erzeugt
replicaset -> pod: erzeugt
route -> service
service -> pod: Label-Selector
configmap -> pod: Env / Volume
secret -> pod: Env / Volume
