...@../../tools/diagrams/style

direction: right

pod: "Pod\n(volumeMount)" {class: resource}
pvc: "PVC\n(Größe, Access Mode)" {class: resource}
pv: "PV\n(Speicher)" {class: store}
sc: "StorageClass\n(Provisioner)" {class: component}

pod -> pvc: nutzt
pvc -> sc: "fordert an" {style.stroke-dash: 4}
sc -> pv: erzeugt
pvc -> pv: gebunden
