...@../../tools/diagrams/style

direction: right

client: Client {class: external}
service: "Service demo\n(stabile IP / DNS-Name)" {class: resource}
pods: "Pods mit Label app=demo" {
  class: group
  p1: Pod 1 {class: resource}
  p2: Pod 2 {class: resource}
  p3: Pod 3 {class: resource}
}

client -> service
service -> pods.p1
service -> pods.p2
service -> pods.p3
